### ISSUE TITLE
`sort_as` not working with contributor ids in page YAML

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/inventories-and-surveys#13]
```
---
label: "Chapter 8"
title: "Develop Survey Tools and Methods"
short_title: 
layout: essay
contributor: 
  - id: jhansen 
    sort_as: "1"
  - id: sdelgadillo
    sort_as: "2"
order: 75
---
```
![Screen Shot 2023-09-20 at 12 58 48 PM](https://github.com/thegetty/inventories-and-surveys/assets/62075223/4ef065ff-c2b0-4167-b732-e8df53444d99)
